name: Validate YAML Files

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  lint-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Create yamllint configuration
        run: |
          cat > .yamllint.yml << EOF
          extends: default
          rules:
            document-start: disable
            indentation:
              spaces: 2
              indent-sequences: true
            line-length:
              max: 120
              level: warning
            trailing-spaces: enable
            new-line-at-end-of-file: enable
            empty-lines:
              max: 2
          EOF

      - name: Lint all YAML files
        run: |
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) -exec yamllint -c .yamllint.yml {} +
