name: Validate YAML Files

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  lint-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: pip install yamllint

      - name: Find and lint YAML files
        run: |
          find . -type f \( -name "*.yml" -o -name "*.yaml" \) -exec yamllint -c .yamllint.yml {} \;
